### ISSUE TITLE
Absolutely zero specs for most things

### ISSUE THREAD

**Issue by AeroNotix** [boundary/folsom#71]
Hi ladies and gents,

Would appreciate if there could be some specs on some of this stuff. Helps the discoverability of your API (is that an atom, a binary or a string argument??).

Any plans for that to come? I'd love to help but without prior knowledge of some of this stuff the only way to see is by extensive examples.

**Comment by joewilliams** [comment]
Folsom has moved, please resubmit your issue at https://github.com/folsom-project Thanks!
