### ISSUE TITLE
Dynamic atoms creation

### ISSUE THREAD

**Issue by kxepal** [boundary/folsom#85]
I wonder what is the reason for Folsom to having dynamic atoms creation for [pid_port_fun_to_atom](https://github.com/boundary/folsom/blob/master/src/folsom_vm_metrics.erl#L283)?

The origin commit says [better string hinting and ip parsing ](https://github.com/boundary/folsom/commit/e11d28fcacefaf30147347d11fef5c994fca762a), but I wonder is this is more important than having your Erlang app crush due to atoms table exhausting.

Yes, I'd read the README and saw the caution:
```
folsom_vm_metrics:get_process_info(). %% use with caution
folsom_vm_metrics:get_port_info(). %% use with caution
```
but this isn't serious since it make pointless providing metrics which you shouldn't use with all cost.

**Comment by joewilliams** [comment]
Folsom has moved, please resubmit your issue at https://github.com/folsom-project Thanks!
